# Generated by Django 2.1.1 on 2018-09-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180929_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxslide',
            name='status',
            field=models.IntegerField(choices=[(1, '线上'), (2, '线下')], default=1),
        ),
    ]
