# Generated by Django 2.1.1 on 2018-09-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180929_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='bxslide',
            name='img',
            field=models.FileField(upload_to='images/bxslider/'),
        ),
    ]
