# Generated by Django 2.1.1 on 2018-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180929_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '线上'), (2, '线下')], default=1)),
                ('weight', models.IntegerField()),
                ('img', models.ImageField(upload_to='static/images/course/')),
                ('name', models.CharField(max_length=40)),
                ('summany', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inform',
            options={'verbose_name': '公告'},
        ),
    ]
