# Generated by Django 2.1.1 on 2018-09-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20180929_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生表'},
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default='1.jpg', upload_to='static/images/avatar/', verbose_name='头像'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.IntegerField(verbose_name='权重'),
        ),
    ]
