# Generated by Django 2.1.1 on 2018-09-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20180929_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='权重')),
                ('letter', models.CharField(max_length=1000, verbose_name='学员感谢信')),
                ('student', models.OneToOneField(on_delete=True, to='app01.Student', verbose_name='学生')),
            ],
        ),
    ]
