# Generated by Django 2.1.1 on 2018-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default='1.jpg', upload_to='./static/images/teacher'),
            preserve_default=False,
        ),
    ]
